//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrolSystem.Models.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetail
    {
        public int ClientID { get; set; }
        public int CompanyID { get; set; }
        public string JobTitle { get; set; }
        public string UserRole { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string CellNo { get; set; }
        public string Email { get; set; }
        public string LogPassword { get; set; }
        public bool AuthorityToCreateSchedule { get; set; }
        public bool AuthorityAddGuards { get; set; }
        public bool AuthorityViewRoster { get; set; }
        public string DateCreated { get; set; }
        public string ActiveStatus { get; set; }
    }
}
