//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrolSystem.Models.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatternTable
    {
        public int PatternID { get; set; }
        public int CompanyID { get; set; }
        public string WorkShift { get; set; }
        public string HoursWorked { get; set; }
        public string ClockInTime { get; set; }
        public string ClockOutTime { get; set; }
    }
}
