//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrolSystem.Models.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTable
    {
        public int id { get; set; }
        public int CompanyID { get; set; }
        public int SiteID { get; set; }
        public int EmployeeID { get; set; }
        public int GuardID { get; set; }
        public int ShiftID { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> ScheduleMonth { get; set; }
        public Nullable<bool> IsHoliday { get; set; }
        public Nullable<bool> IsSunday { get; set; }
        public string Availability { get; set; }
        public int noDays { get; set; }
    }
}
