//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrolSystem.Models.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTable
    {
        public int ScheduleID { get; set; }
        public int SiteID { get; set; }
        public int EmployeeID { get; set; }
        public string WordShift { get; set; }
        public string RequestedDays { get; set; }
        public string Availability { get; set; }
    }
}
