//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrolSystem.Models.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteTable
    {
        public int SiteID { get; set; }
        public int CompanyID { get; set; }
        public string SiteName { get; set; }
        public string Location { get; set; }
        public string Period { get; set; }
        public string TempPeriodMonths { get; set; }
        public string ShiftsRequired { get; set; }
        public string GuardsPerShift { get; set; }
    }
}
