//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public int CompanyID { get; set; }
        public int MasterID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string PaymentDay { get; set; }
        public string PaymentStatus { get; set; }
        public int Level { get; set; }
        public string ActiveStatus { get; set; }
        public string DateCreated { get; set; }
    }
}
